# Generated by Django 2.2 on 2020-06-25 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mytasks',
            old_name='task_date',
            new_name='task_due_date',
        ),
    ]
